version: '3.8'

services:
  app:
    image: ghcr.io/mikhail-angelov/abnative-test-demo:latest
    container_name: abnative
    restart: unless-stopped
    ports:
      - "127.0.0.1:3021:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
